fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    docker: "https://github.com/puppetlabs/puppetlabs-docker.git" 
  symlinks:
    docker_ddc: "#{source_dir}"
